name: terraform-docs
version: "0.16.0"
summary: Terraform Docs Generate Terraform modules documentation in various formats
license: MIT
contact: am6puk@gmail.com
issues: https://github.com/am6puk/terraform-docs/issues
source-code: https://github.com/am6puk/terraform-docs
website: https://terraform-docs.io/
description: |
  Terraform Docs - A utility to generate documentation from Terraform modules in various output formats.
base: core22
grade: stable
confinement: strict
compression: lzo

apps:
  terraform:
    command: terraform-docs
    plugs: 
        - home

architectures:
  - build-on: amd64
#  - build-on: armhf
  - build-on: arm64
  - build-on: s390x
#  - build-on: ppc64el

parts:
  terraform:
    plugin: go
    source: https://github.com/terraform-docs/terraform-docs
    source-type: git
    source-tag: "v$SNAPCRAFT_PROJECT_VERSION"
    build-snaps: [go]
    # build-environment:
    #   - CGO_ENABLED: "0"
    #   - GOFLAGS: "-mod=readonly"
    override-build: |
      make build
      cp bin/linux-$SNAP_ARCH/terraform-docs $SNAPCRAFT_PART_INSTALL/terraform-docs
    stage:
      - terraform-docs